### ISSUE TITLE
Criar imagem para colocar na Organization no Github

### ISSUE THREAD

**Issue by rodrigopinto** [desenvolvimentoagilcombr/desenvolvimentoagilcombr.github.com#34]
Gerar o ícone para colocar na imagem da organization no github.

**Comment by fernandoguedes** [comment]
@rodrigopinto, subi um commit (PR #37)  pra atender essa issue.

**Comment by rodrigopinto** [comment]
@fernandoguedes Opa, vou passar pra galera! ;) o/ :+1:

**Comment by rodrigopinto** [comment]
@maurogeorge pode ver de colocar essa imagem na organization?

**Comment by maurogeorge** [comment]
@rodrigopinto acho que não tenho poderes suficientes, sou do mesmo team que você https://github.com/orgs/desenvolvimentoagilcombr/teams

**Comment by maurogeorge** [comment]
O ícone foi criado e adicionado a organization. Fechando a issue.
