### ISSUE TITLE
Atualizar informações sobre a certificação Scrum.

### ISSUE THREAD

**Issue by landrade** [desenvolvimentoagilcombr/desenvolvimentoagilcombr.github.com#36]
Atualizar as informações do link http://www.desenvolvimentoagil.com.br/scrum/certificacao.

Hoje para se tornar certificado CSM por qualquer "instituição" é necessário fazer uma prova e ter uma porcentagem mínima de acertos.
Apenas no caso da Scrum Alliance é pré-requisito ter feito o curso CSM certificado por eles.

**Comment by rodrigopinto** [comment]
Resolvido no commit ab8258bddd4507cf3507f73bd6000dc3eac1999.
